### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by vcl00e** [ashneo76/generator-gradle-react#1]
Hi can you please update the gradle gulp version in your build.gradle file? version 0.10 has a bug that causes build to fail on npnInstall. I'm using windows and I'm not sure if this problem is specific to windows.

I've patched my local build.gradle file with the following to fix it. 

classpath("com.moowork.gradle:gradle-gulp-plugin:0.10")

with

classpath("com.moowork.gradle:gradle-gulp-plugin:0.13")
classpath("com.moowork.gradle:gradle-node-plugin:0.13")

**Comment by ashneo76** [comment]
Definitely. Thank you for reporting back!

**Comment by ashneo76** [comment]
It could also be the gradle version. I have updated that as well.

**Comment by ashneo76** [comment]
#e6f051f59c1084b6d1e5e0144728d7eb32699649

**Comment by ashneo76** [comment]
Since I don't have workflow setup for this repo yet, the commit #e6f051f59c1084b6d1e5e0144728d7eb32699649 fixes it.

**Comment by vcl00e** [comment]
Cheers thanks :)
